version: '3.8'

services:
  back:
    image: java_backend:latest
    build: ./backend/
    networks:
      - def
    depends_on:
      - database
    restart: unless-stopped
    
  front:
    image: node-frontend:latest
    build: ./frontend/
    restart: unless-stopped
    depends_on: 
      - back  
    networks:
      - def
      
  database:
    image: mysql:${DB_IMAGE}
    restart: unless-stopped
    env_file: .env
    networks: 
      - def
    volumes:
      - mysql:/var/lib/mysql 
      
  nginx:
    image: nginx:${NGINX_IMAGE}
    restart: unless-stopped
    networks: 
      -  def 
    ports:
      - "8080:8080"
      - "80:80"
    volumes: 
      - ./nginx:/etc/nginx/conf.d
    env_file: .env
    depends_on:
      - frontend   
      - backend  

networks:
   def:
      driver: bridge

volumes: 
  mysql:
    name: dbsql
